controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\ApiController::index

create_user:
    path: /users/create
    controller: App\Controller\UserController::create
    methods: POST

read_user:
    path: /users/read/{id}
    controller: App\Controller\UserController::read
    methods: GET

read_users:
    path: /users/read
    controller: App\Controller\UserController::readAll
    methods: GET

update_user:
    path: /users/update
    controller: App\Controller\UserController::update
    methods: POST

delete_user:
    path: /users/delete
    controller: App\Controller\UserController::delete
    methods: POST


